### ISSUE TITLE
npm install issue with workshopper

### ISSUE THREAD

**Issue by jbelmont** [phase2/pattern-lab-workshop#10]
Hello I am trying to do the pattern-lab-workshop but I am receiving this error

➜  pattern-lab-workshop npm install -g pattern-lab-workshop
npm ERR! git clone --template=/Users/jbelmont/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tjheffner/workshopper.git /Users/jbelmont/.npm/_git-remotes/ssh-git-github-com-tjheffner-workshopper-git-47fbfcd9: Cloning into bare repository '/Users/jbelmont/.npm/_git-remotes/ssh-git-github-com-tjheffner-workshopper-git-47fbfcd9'...
npm ERR! git clone --template=/Users/jbelmont/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tjheffner/workshopper.git /Users/jbelmont/.npm/_git-remotes/ssh-git-github-com-tjheffner-workshopper-git-47fbfcd9: Permission denied (publickey).
npm ERR! git clone --template=/Users/jbelmont/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tjheffner/workshopper.git /Users/jbelmont/.npm/_git-remotes/ssh-git-github-com-tjheffner-workshopper-git-47fbfcd9: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/jbelmont/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tjheffner/workshopper.git /Users/jbelmont/.npm/_git-remotes/ssh-git-github-com-tjheffner-workshopper-git-47fbfcd9:
npm ERR! git clone --template=/Users/jbelmont/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tjheffner/workshopper.git /Users/jbelmont/.npm/_git-remotes/ssh-git-github-com-tjheffner-workshopper-git-47fbfcd9: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/jbelmont/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tjheffner/workshopper.git /Users/jbelmont/.npm/_git-remotes/ssh-git-github-com-tjheffner-workshopper-git-47fbfcd9: and the repository exists.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "pattern-lab-workshop"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/jbelmont/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tjheffner/workshopper.git /Users/jbelmont/.npm/_git-remotes/ssh-git-github-com-tjheffner-workshopper-git-47fbfcd9
npm ERR! Cloning into bare repository '/Users/jbelmont/.npm/_git-remotes/ssh-git-github-com-tjheffner-workshopper-git-47fbfcd9'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jbelmont/nodeschool.io/pattern-lab-workshop/npm-debug.log

**Comment by randychampagne** [comment]
Hello, I experienced the same issue. Any update will be greatly appreciated.

**Comment by robbiethegeek** [comment]
Are you still experiencing this : Now using node v4.2.4
╭─robbie@Robbies-MacBook-Pro.local ~/Repos/personal/pattern-lab-workshop
╰─➤  npm --version
2.14.12
╭─robbie@Robbies-MacBook-Pro.local ~/Repos/personal/pattern-lab-workshop
╰─➤  npm install -g pattern-lab-workshop
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
/Users/robbie/.nvm/versions/node/v4.2.4/bin/pattern-lab-workshop -> /Users/robbie/.nvm/versions/node/v4.2.4/lib/node_modules/pattern-lab-workshop/pattern-lab.js
pattern-lab-workshop@1.0.4 /Users/robbie/.nvm/versions/node/v4.2.4/lib/node_modules/pattern-lab-workshop
├── marked@0.3.5
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── concat-stream@1.2.1 (bops@0.0.6)
├── ecstatic@0.5.8 (he@0.5.0, mime@1.3.4, minimist@1.2.0)
├── request@2.30.0 (aws-sign2@0.5.0, tunnel-agent@0.3.0, forever-agent@0.5.2, qs@0.6.6, oauth-sign@0.3.0, mime@1.2.11, json-stringify-safe@5.0.1, node-uuid@1.4.7, http-signature@0.10.1, tough-cookie@0.9.15, form-data@0.1.4, hawk@1.0.0)
├── cheerio@0.17.0 (entities@1.1.1, lodash@2.4.2, dom-serializer@0.0.1, CSSselect@0.4.1, htmlparser2@3.7.3)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
└── workshopper-jlord@0.1.0 (map-async@0.1.1, tuple-stream@0.0.2, split@0.2.10, through@2.3.8, mkdirp@0.3.5, colors-tmpl@0.1.1, terminal-menu@0.2.0, xtend@2.1.2, shelljs@0.5.3, optimist@0.6.1, msee@0.1.2, lodash@3.10.1)

**Comment by randychampagne** [comment]
Tnx for the update Robbie. I will check this evening and let you know

**Comment by randychampagne** [comment]
Ok so I switched to node v4.2.4 (npm v2.14.12) but experienced the same issue when installing the standard npm package
`npm install -g pattern-lab-workshop`

But I was able to complete the install using @finnp's build posted [here](https://github.com/nodeschool/discussions/issues/1703)
`npm i finnp/pattern-lab-workshop#fixdep -g`

I suppose the standard install will work again when these changes are merged.

**Comment by robbiethegeek** [comment]
Will review this AM.

**Comment by robbiethegeek** [comment]
Pretty sure this is resolved in 1.0.5 please try again.

**Comment by EvanLovely** [comment]
This should all of been fixed by #12 — give it another shot!

**Comment by randychampagne** [comment]
Yep all good. I was able to install with `npm i -g pattern-lab-workshop`

Thank you all🤘🏾
